### ISSUE TITLE
Lack of build and test instructions.

### ISSUE THREAD

**Issue by rprobaina** [gabrieltassinari/lsysmon#1]
Hi Gabriel,

I'd love to have a chance to test this project. However, I couldn't find any building and testing instructions in the README.md file. Would you mind providing such details?

Best regards,
Ricardo

**Comment by gabrieltassinari** [comment]
Hi @rprobaina,

Thanks for your idea!

I have added some instructions in the [README](https://github.com/gabrieltassinari/lsysmon/blob/main/README.md), if it isn't clear or you have any problem on testing it feel free to leave a comment or make another issue.

Sincerely,
Gabriel

**Comment by rprobaina** [comment]
Thanks, Gabriel!
